source $HOME/dotfiles/vimrc.d/vimrc.ale
source $HOME/dotfiles/vimrc.d/vimrc.basic
source $HOME/dotfiles/vimrc.d/vimrc.colors
source $HOME/dotfiles/vimrc.d/vimrc.dirvish
source $HOME/dotfiles/vimrc.d/vimrc.fzf
source $HOME/dotfiles/vimrc.d/vimrc.indent
source $HOME/dotfiles/vimrc.d/vimrc.maps
source $HOME/dotfiles/vimrc.d/vimrc.statusline
source $HOME/dotfiles/vimrc.d/vimrc.vimwiki
