require("plugins")
require("settings")
require("mappings")
require("statusline")

require("plugins/fzf")
require("plugins/nvim-cmp")
require("plugins/nvim-treesitter")
require("plugins/gitmessenger")
require("plugins/dirvish")
require("plugins/nvim-lsp-installer")
require("plugins/nvim-lsp")
require("plugins/sneak")
